const COMMANDS: &[&str] = &[
    "bootstrap",
    "catalog",
    "activate_project",
    "refresh_project",
    "start_daemon",
    "stop_daemon",
    "register_gui_caller",
    "decide_approval",
    "load_evidence",
    "load_flow_workspace",
    "daemon_activity",
    "daemon_logs",
    "daemon_stats",
    "caller_registry",
    "model_status",
    "model_infer",
    "model_import",
    "model_import_status",
    "model_inspect",
    "model_presets",
    "model_download",
    "model_download_status",
    "model_download_cancel",
    "host_memory",
    "app_settings",
    "settings_update",
    "logs_delete",
    "reveal_path",
    "flow_graph",
    "flow_compose",
    "load_skill_inventory",
    "manage_skill_library",
    "load_skill_audit",
    "run_skill_audit",
    "open_flow",
    "validate_flow",
    "save_flow",
    "connector_registry",
    "connector_configure",
    "connector_test",
    "daemon_health",
];

fn main() {
    let manifest = tauri_build::AppManifest::new().commands(COMMANDS);
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(manifest))
        .expect("failed to build the PAM desktop shell");
}
