[package]
name = "pam-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
name = "pam_desktop"
path = "src/lib.rs"

[[bin]]
name = "pam"
path = "src/main.rs"

[build-dependencies]
tauri-build.workspace = true

[dependencies]
pam_cli.workspace = true
pam_gui.workspace = true
serde.workspace = true
tauri.workspace = true
tauri-plugin-dialog = "2"

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
