[package]
name = "pam_daemon"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
cap-fs-ext.workspace = true
cap-std.workspace = true
pam_connectors.workspace = true
pam_core.workspace = true
pam_flow.workspace = true
pam_model.workspace = true
pam_platform.workspace = true
pam_policy.workspace = true
pam_protocol.workspace = true
pam_store.workspace = true
rmp-serde.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true

[target.'cfg(unix)'.dependencies]
nix = { workspace = true, features = ["process", "signal", "user"] }

[dev-dependencies]
rusqlite.workspace = true
zeromq.workspace = true

[lints]
workspace = true
