[package]
name = "pam_connectors"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
pam_compact.workspace = true
pam_core.workspace = true
pam_policy.workspace = true
pam_store.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
url.workspace = true

[lints]
workspace = true
