[package]
name = "pam_cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
cap-fs-ext.workspace = true
cap-std.workspace = true
clap.workspace = true
directories.workspace = true
pam_client.workspace = true
pam_core.workspace = true
pam_daemon.workspace = true
pam_flow.workspace = true
pam_model.workspace = true
pam_platform.workspace = true
pam_policy.workspace = true
pam_protocol.workspace = true
pam_skills.workspace = true
pam_store.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
uuid.workspace = true

[lints]
workspace = true
